trigger:
- nomain

pool:
  name: Default
  demands:
   - agent.name -equals local-pc 

stages:
- stage: stage1

  ## Jobs inside Stage
  jobs:

  ### CI Job
  - job: createStorage
    #### Steps inside the Job
    steps:

    # Check and remove any existing Python installations
    - task: CmdLine@2
      name: CheckAndRemovePython
      displayName: 'Check and Remove Existing Python Installation'
      inputs:
        script: |
          echo Checking for existing Python installation...
          where python
          if %ERRORLEVEL% NEQ 0 (
            echo "No existing Python installation found."
          ) else (
            echo "Existing Python installation found."
            for /f "tokens=*" %%a in ('where python') do (
              echo "Removing Python installation at %%a"
              rmdir /s /q "%%~dpa"
            )
          )

    # Install Python if not already installed
    - task: CmdLine@2
      name: InstallPython
      displayName: 'Install Python'
      inputs:
        script: |
          echo Installing Python...
          curl -o python-installer.exe https://www.python.org/ftp/python/3.9.6/python-3.9.6-amd64.exe
          python-installer.exe /quiet InstallAllUsers=1 PrependPath=1 /log install.log
          type install.log
          if exist "C:\Python39\python.exe" ( 
              set "PYTHON_PATH=C:\Python39" 
          ) else (
              echo "Python installation failed."
              exit 1
          )
          set "PATH=%PATH%;%PYTHON_PATH%\Scripts;%PYTHON_PATH%"

    # Install AWS CLI
    - task: CmdLine@2
      name: InstallAWSCLI
      displayName: 'Install AWS CLI'
      inputs:
        script: |
          echo Installing AWS CLI...
          curl "https://awscli.amazonaws.com/AWSCLIV2.msi" -o "AWSCLIV2.msi"
          msiexec.exe /i AWSCLIV2.msi /quiet
          if exist "C:\Program Files\Amazon\AWSCLIV2\aws.exe" ( 
              set "AWS_CLI_PATH=C:\Program Files\Amazon\AWSCLIV2" 
          ) else (
              echo "AWS CLI installation failed."
              exit 1
          )
          set "PATH=%PATH%;%AWS_CLI_PATH%"

    # Configure AWS credentials
    - task: CmdLine@2
      name: ConfigureAWSCredentials
      displayName: 'Configure AWS CLI credentials'
      inputs:
        script: |
          echo Configuring AWS credentials...
          aws configure set aws_access_key_id %aws_id%
          aws configure set aws_secret_access_key %aws_access_key%
          aws configure set default.region us-east-1

    # Create S3 bucket
    - task: CmdLine@2
      name: createS3
      displayName: 'Create S3 bucket'
      inputs:
        script: |
          cd az-devops\aws-ep7
          %PYTHON_PATH%\python -m venv env
          call env\Scripts\activate.bat
          %PYTHON_PATH%\Scripts\pip install awscli
          aws s3api create-bucket --bucket dl-azdevops-ep7 --region us-east-1
          deactivate

  # CD Job
  - job: uploadJob
    dependsOn: createStorage
    #### Steps inside the Job
    steps:

    - task: CmdLine@2
      name: uploadToS3
      displayName: 'Upload files to S3 bucket'
      inputs:
        script: |
          cd az-devops\aws-ep7
          call env\Scripts\activate.bat
          %PYTHON_PATH%\Scripts\pip install awscli
          aws s3 sync . s3://dl-azdevops-ep7
          deactivate
