trigger:
- nomain

pool:
  name: Default
  demands:
   - agent.name -equals local-pc 

stages:
- stage: stage1

  ## Jobs inside Stage
  jobs:

  ### CI Job
  - job: manageModelOutputs
    #### Steps inside the Job
    steps:

    # Step 1: Create a folder called "model_outputs" and a file "champion_model.pt" inside it
    - task: CmdLine@2
      name: CreateModelOutputs
      displayName: 'Create model_outputs folder and champion_model.pt file'
      inputs:
        script: |
          echo Creating model_outputs folder...
          mkdir C:\agent\_work\model_outputs
          echo Creating champion_model.pt file...
          echo. > C:\agent\_work\model_outputs\champion_model.pt

    # Step 2: Create a file "model_modified.txt" with flag "True"
    - task: CmdLine@2
      name: CreateFlagFile
      displayName: 'Create model_modified.txt file with flag "True"'
      inputs:
        script: |
          echo Creating model_modified.txt file...
          echo True > C:\agent\_work\model_outputs\model_modified.txt

    # Step 3: Check if the flag is "True" and copy the model_outputs folder to the local build agent
    - task: CmdLine@2
      name: CheckAndCopyFiles
      displayName: 'Check flag and copy files to local build agent'
      inputs:
        script: |
          echo Checking model_modified.txt flag...
          set /p FLAG=<C:\agent\_work\model_outputs\model_modified.txt
          if "%FLAG%"=="True" (
            echo Copying model_outputs folder to local build agent...
            xcopy C:\agent\_work\model_outputs C:\agent\_work\_model_outputs_copy /s /e /y
            echo Flag is True. Changing flag in copied model_modified.txt to False...
            echo False > C:\agent\_work\_model_outputs_copy\model_modified.txt
          ) else (
            echo Flag is not True. No action taken.
          )
