trigger:
- nomain

pool:
  name: Default
  demands:
   - agent.name -equals local-pc 

stages:
- stage: stage1

  ## Jobs inside Stage
  jobs:

  ### CI Job
  - job: createStorage
    #### Steps inside the Job
    steps:

    - task: CmdLine@2
      name: createS3
      displayName: 'Create S3 bucket'
      inputs:
        script: |
          cd az-devops\aws-ep7
          python -m venv env
          call env\Scripts\activate.bat
          pip install awscli
          set AWS_ACCESS_KEY_ID=%aws_id%
          set AWS_SECRET_ACCESS_KEY=%aws_access_key%
          aws s3api create-bucket --bucket dl-azdevops-ep7 --region us-east-1
          deactivate

  # CD Job
  - job: uploadJob
    dependsOn: createStorage
    #### Steps inside the Job
    steps:

    - task: CmdLine@2
      name: uploadToS3
      displayName: 'Upload files to S3 bucket'
      inputs:
        script: |
          cd az-devops\aws-ep7
          python -m venv env
          call env\Scripts\activate.bat
          pip install awscli
          set AWS_ACCESS_KEY_ID=%aws_id%
          set AWS_SECRET_ACCESS_KEY=%aws_access_key%
          aws s3 sync . s3://dl-azdevops-ep7
          deactivate
